<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class TestUpdate extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array|string>
     */
    public function rules(): array
    {
        return [
            'name'=>'required|string|max:255',
            'content'=>'required|string|max:255',
            'photo '=>'sometimes|nullable|file|image',
        ];
    }
    public function attributes()
    {
        return [
            'name'=>'Name',
            'content'=>'Content',
            'photo'=>'Photo'
        ]; // TODO: Change the autogenerated stub
    }
}
